#pragma once

/**
 * inference.h — Random Forest inference wrapper.
 *
 * Takes a FeatureVector (output of event.h), applies StandardScaler
 * normalization, runs the RF classifier, and returns the predicted class
 * and inference time in microseconds.
 *
 * Dependencies: rf_model.h, scaler.h (generated by sklearn-porter / Eloquent)
 *
 * Usage
 * ─────
 *   InferenceResult res = infer(fv);
 *   Serial.printf("[INF] class=%d  time=%lu us\n", res.label, res.elapsed_us);
 *   networkPublish(&res, MQTT_TOPIC_INFERENCE, sizeof(res));
 */

#include <Arduino.h>
#include "model_interface.h"
#include "event.h"

// ── Result ────────────────────────────────────────────────────
struct InferenceResult {
    uint32_t timestamp_ms;
    uint32_t session_id;
    int32_t  label;
    uint32_t elapsed_us;
    const char* label_name;
};

// ── Model instance ────────────────────────────────────────────
namespace inference_detail {
    Eloquent::ML::Port::RandomForest _clf;
} // namespace inference_detail

// ── Public API ────────────────────────────────────────────────

/**
 * Run inference on a FeaturePacket.
 *
 *   1. Copy features into a local buffer (preserves fv intact).
 *   2. Apply StandardScaler: x = (x - mean) / scale.
 *   3. Call clf.predict().
 *   4. Return label + timing.
 */
InferenceResult infer(const FeaturePacket& fv) {




    // 1. Copy + normalize
    float features[FEATURE_COUNT];
    for (int i = 0; i < FEATURE_COUNT; i++)
        features[i] = (fv.features[i] - SCALER_MEAN[i]) / SCALER_SCALE[i];
    

//                 static const char* FEATURE_NAMES[FEATURE_COUNT] = {
//     "gx_mean", "gx_std", "gx_min", "gx_max", "gx_energy",
//     "gy_mean", "gy_std", "gy_min", "gy_max", "gy_energy",
//     "gz_mean", "gz_std", "gz_min", "gz_max", "gz_energy",
//     "ax_mean", "ax_std", "ax_min", "ax_max", "ax_energy",
//     "ay_mean", "ay_std", "ay_min", "ay_max", "ay_energy",
//     "az_mean", "az_std", "az_min", "az_max", "az_energy"
// };

// Serial.println("\n=== FEATURE VECTOR ===");
// for (int i = 0; i < FEATURE_COUNT; i++) {
//     Serial.printf("[%02d] %-10s = %12.6f\n",
//                   i,
//                   FEATURE_NAMES[i],
//                   features[i]);
// }
// Serial.println("======================");

    // 2. Predict
    uint32_t t0 = micros();
    int label = inference_detail::_clf.predict(features);
    uint32_t t1 = micros();

    return {
        millis(),
        fv.session_id,
        (int32_t)label,
        t1 - t0,
        get_class_name(label)
    };
}