; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; https://docs.platformio.org/page/projectconf.html

; =========================================================
; TEENSY 4.1
; =========================================================

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
monitor_speed = 115200

lib_deps = 
    knolleary/PubSubClient @ ^2.8.0
    jrowberg/I2Cdevlib-Core
    jrowberg/I2Cdevlib-MPU6050
    https://github.com/mikalhart/TinyGPSPlus
    https://github.com/ssilverman/QNEthernet

build_flags =
    -O2
    -DTF_LITE_STATIC_MEMORY
    -Ilib/tflm
    -Ilib/tflm/third_party/flatbuffers/include
    -Ilib/tflm/third_party/gemmlowp
    -Ilib/tflm/third_party/ruy
    -Ilib/tflm/third_party/kissfft


; =========================================================
; ESP32 DEV KIT (MATCHED CONFIG)
; =========================================================

; [env:esp32dev]
; platform = espressif32
; board = esp32dev
; framework = arduino
; monitor_speed = 115200

; lib_deps = 
;     knolleary/PubSubClient @ ^2.8.0
;     jrowberg/I2Cdevlib-Core
;     jrowberg/I2Cdevlib-MPU6050
;     https://github.com/mikalhart/TinyGPSPlus

; build_flags =
;     -O2
;     -DTF_LITE_STATIC_MEMORY
;     -Ilib/tflm
;     -Ilib/tflm/third_party/flatbuffers/include
;     -Ilib/tflm/third_party/gemmlowp
;     -Ilib/tflm/third_party/ruy
;     -Ilib/tflm/third_party/kissfft